### ISSUE TITLE
[Bug]: Plugin is incompatible to nx

### ISSUE THREAD

**Issue by iceteabottle** [chiefmikey/eslint-plugin-disable-autofix#4]
### What happened?

I'm currently working in a bigger project using an [nx monorepo](https://nx.dev/) with several angular apps and discovered that your plugin isn't compatible. It searches the other installed es lint rules in the wrong directory. See the full exception in the log output below.
There's no node_modules directory in: `/apps/my-app`
There's only one node_modules directory in the root dir.

Sorry, maybe it's more a feature request than a bug report. Please think about the nx compatibility.
Thanks!

### Version

3.0.0

### Relevant log output

```shell
Error: Failed to load plugin 'disable-autofix' declared in '.eslintrc.json » ../../.eslintrc.json#overrides[2]': ENOENT: no such file or directory, scandir '/Users/username/dev/project/mono-repo/apps/my-app/node_modules/eslint/lib/rules'

Error: Failed to load plugin 'disable-autofix' declared in '.eslintrc.json » ../../.eslintrc.json#overrides[2]': ENOENT: no such file or directory, scandir '/Users/username/dev/project/mono-repo/apps/my-app/node_modules/eslint/lib/rules'
at Object.readdirSync (node:fs:1390:3)
at Object.<anonymous> (/Users/username/dev/project/mono-repo/node_modules/eslint-plugin-disable-autofix/lib/rules.js:18:6)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/Users/username/dev/project/mono-repo/node_modules/eslint-plugin-disable-autofix/lib/index.js:4:15)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
Process finished with exit code -1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chiefmikey** [comment]
Thanks for opening this issue, I'm working on a compatibility fix at the moment and will definitely consider this in the implementation!

**Comment by chiefmikey** [comment]
Resolved by #7

**Comment by iceteabottle** [comment]
@chiefmikey when do you plan to release a version?
I would love to implement it finally in our nx project :)

**Comment by chiefmikey** [comment]
It has been released in https://github.com/chiefmikey/eslint-plugin-disable-autofix/releases/tag/v3.1.1

@iceteabottle If you're able to, please let me know if you come across any issues. Testing with nx has been limited so far. Thanks!

**Comment by iceteabottle** [comment]
@chiefmikey sadly strange things are happening. Only by adding the plugin to the plugin section in the `.eslintrc` all my rules with "warn" severity are now marked as errors. It doesn't matter if it's the root `.eslintrc` or a project specific one (like for an app).
But the main feature of your plugin works like a charm^^

**Comment by chiefmikey** [comment]
@iceteabottle If you can, please provide any information about your repo that might help me recreate the issue. Thanks!
