### ISSUE TITLE
[Bug]: no typescript declaration file

### ISSUE THREAD

**Issue by Zamiell** [chiefmikey/eslint-plugin-disable-autofix#53]
Hello and thanks for the plugin.

Now that ESLint 9 is released and everyone is migrating to flat config, importing the plugin into a flat config by following the official documentation actually results in a red squiggly line, because no declaration file exists (when using checkJs and/or @ts-check).

I suspect many/most users will be using TypeScript to validate that their new flat configs do not have typos in them. Thus, shipping a declaration file for this plugin would really be appreciated!

### Version

5.0.1

**Comment by Zamiell** [comment]
Additionally, this project does not have anything to do with browsers, so having a "What browsers are you seeing the problem on?" as part of the issue template seems like a bug.

**Comment by chiefmikey** [comment]
@Zamiell thank you for taking the time to detail these issues, I will look into them as soon as possible
