### ISSUE TITLE
[Bug]: Error: Failed to load plugin 'disable-autofix' declared in '.eslintrc.js'

### ISSUE THREAD

**Issue by Slapbox** [chiefmikey/eslint-plugin-disable-autofix#9]
### What happened?

Followed setup instructions - even putting `disable-autofix` plugin first - but it just throws the error: `Error: Failed to load plugin 'disable-autofix' declared in '.eslintrc.js'`

Occurs on a Linux development machine.

### Version

3.1.1

### Relevant log output

```shell
Error: Failed to load plugin 'disable-autofix' declared in '.eslintrc.js'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Slapbox** [comment]
Actually I was only getting this when we had the deprecated `eslint-plugin-emotion` in our `package.json` (although it was not in our `.eslintrc.js`. After removing it, ESLint fails silently instead. If I run it with `--debug` it lists out all the rules, then exits with code 1, having done nothing but enumerate the rules.

Any ideas would be greatly appreciated! Thanks for your work on this project @chiefmikey.

**Comment by Slapbox** [comment]
Friendly bump

**Comment by chiefmikey** [comment]
@Slapbox Sorry for the delayed response, there is a bug with eslint base rules being handled differently depending on the version of eslint. I'm working on a patch and will release a fix asap.

**Comment by tbjgolden** [comment]
We ran into this - downgraded to 3.0.0 to avoid the issue.

We noticed it only occurred on our devs using Windows, so that might be related - or not - just fyi.

**Comment by chiefmikey** [comment]
@tbjgolden Thanks for the heads up, hoping to have this resolved soon.

**Comment by sergiop** [comment]
I ran into the same issue upgrading `@typescript-eslint/eslint-plugin` to `^6.0.0`. I had `eslint@^8.4.1` and upgrading to the latest version seems to have solved.

**Comment by sergiop** [comment]
@chiefmikey the solution provided by @ezpuzz seems working, could you please give it a check?

https://github.com/chiefmikey/eslint-plugin-disable-autofix/pull/11

**Comment by chiefmikey** [comment]
Thank you for the much appreciated patience, v4.0.0 includes @ezpuzz 's path fix along with an overhaul that should have the plugin functioning as it did in earlier versions.
